# Generated by Django 5.1.1 on 2024-09-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
