# Generated by Django 3.1.14 on 2024-12-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20241230_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='farmer_card',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer'), ('outlet', 'outlet'), ('franchisee', 'Franchisee')], max_length=10),
        ),
    ]
