# Generated by Django 3.1.14 on 2025-01-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_auto_20241231_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_file',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='farmer_file',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_images/'),
        ),
    ]
