# Generated by Django 3.1.14 on 2025-01-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_auto_20250102_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='farmer_files/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='aadhaar_file',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_files/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='farmer_file',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_files/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_files/'),
        ),
    ]
