# Generated by Django 3.1.14 on 2025-01-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_auto_20250102_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhaar_file',
            field=models.FileField(blank=True, null=True, upload_to='farmer_files/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='farmer_file',
            field=models.FileField(blank=True, null=True, upload_to='farmer_files/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='farmer_files/'),
        ),
    ]
