# Generated by Django 3.1.14 on 2025-01-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_auto_20250102_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pancard',
            field=models.FileField(blank=True, null=True, upload_to='farmer_files/'),
        ),
    ]
