# Generated by Django 3.1.14 on 2025-01-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0012_customuser_pancard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pancard_file',
            field=models.FileField(blank=True, null=True, upload_to='farmer_files/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pancard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
