# Generated by Django 3.1.14 on 2025-01-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0013_auto_20250122_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='crop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='land_location',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='land_owner',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='land_photo',
            field=models.FileField(blank=True, null=True, upload_to='farmer_files/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='land_size',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sand_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='yield_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
